# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/onter/project/hub/minloadblance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/onter/project/hub/minloadblance

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onter/project/hub/minloadblance/CMakeFiles /home/onter/project/hub/minloadblance/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onter/project/hub/minloadblance/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minloadblance

# Build rule for target.
minloadblance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minloadblance
.PHONY : minloadblance

# fast build rule for target.
minloadblance/fast:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/build
.PHONY : minloadblance/fast

log.o: log.cpp.o

.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i

.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s

.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/main.cpp.s
.PHONY : main.cpp.s

xml/tinyxml2.o: xml/tinyxml2.cpp.o

.PHONY : xml/tinyxml2.o

# target to build an object file
xml/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/xml/tinyxml2.cpp.o
.PHONY : xml/tinyxml2.cpp.o

xml/tinyxml2.i: xml/tinyxml2.cpp.i

.PHONY : xml/tinyxml2.i

# target to preprocess a source file
xml/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/xml/tinyxml2.cpp.i
.PHONY : xml/tinyxml2.cpp.i

xml/tinyxml2.s: xml/tinyxml2.cpp.s

.PHONY : xml/tinyxml2.s

# target to generate assembly for a file
xml/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/minloadblance.dir/build.make CMakeFiles/minloadblance.dir/xml/tinyxml2.cpp.s
.PHONY : xml/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... minloadblance"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... xml/tinyxml2.o"
	@echo "... xml/tinyxml2.i"
	@echo "... xml/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

